<template>
  <div class="detail-content">
    <div class="detail-box-wrap">
      <div class="detail-title">Definition of SASEUL nodes</div>
      <div class="detail-line"></div>
      <div class="detail-box-1">
        <div class="detail-img-box">
          <img
            src="../../assets/infographic/box_lightnode.png"
            height="50"
            width="50"
          />
        </div>
        <div class="detail-text-box">
          <div class="m_box">
            <div class="m_box_lightnode"></div>
          </div>
          <span class="detail-bold-text">Light node</span><br />
          Light nodes are the most basic and simple nodes on the network. They
          are directly related to blockchain wallet and practical services for
          the end users who do not actively contribute to the network. Each node
          has its unique private key and tracker and is capable of requesting
          transactions and viewing the transaction results.
        </div>
      </div>
      <div class="detail-box-1">
        <div class="detail-img-box">
          <img
            src="../../assets/infographic/box_supervisor.png"
            height="50"
            width="50"
          />
        </div>
        <div class="detail-text-box">
          <div class="m_box">
            <div class="m_box_supervisor"></div>
          </div>
          <span class="detail-bold-text">Supervisor</span><br />
          Supervisors are nodes that sync all existing blocks on the network.
          They differ from light nodes because they are meant to monitor and
          supervise the blockchain network. The supervisors check whether the
          network has generated a valid block and store the block if they are
          valid. They are capable of detecting erroneous hash values but they do
          not directly form transactions that confirm the error or punish the
          evil nodes.
        </div>
      </div>
      <div class="detail-box-1">
        <div class="detail-img-box">
          <img
            src="../../assets/infographic/box_validator.png"
            height="50"
            width="50"
          />
        </div>
        <div class="detail-text-box">
          <div class="m_box">
            <div class="m_box_validator"></div>
          </div>
          <span class="detail-bold-text">Validator</span><br />
          Validators also sync all existing blocks on the network and are
          authorized to participate in the consensus process. They are capable
          of receiving transaction requests and either accepting or denying them
          based on consensus to generate data in a block form. The fundamental
          consensus is derived from the SASEUL Consensus Algorithm. Validators
          communicate directly with light nodes, periodically hash generated
          blocks, and transfer those blocks to the arbiters.
        </div>
      </div>
      <div class="detail-box-1">
        <div class="detail-img-box">
          <img
            src="../../assets/infographic/box_arbiter.png"
            height="50"
            width="50"
          />
        </div>
        <div class="detail-text-box">
          <div class="m_box">
            <div class="m_box_arbiter"></div>
          </div>
          <span class="detail-bold-text">Arbiter</span><br />
          Arbiters are storage nodes for all blocks created in the network. do
          not participate in the consensus process. The only responsibility they
          have is sending past data when a validator requests them for reference
          during validation.
        </div>
      </div>
    </div>

    <div class="detail-box-wrap">
      <div class="detail-title">Scheme of SASEUL Network</div>
      <div class="detail-line"></div>
      <div class="detail-box-2">
        <img src="../../assets/infographic/overall_scheme.png" />
      </div>
    </div>

    <div class="detail-box-wrap">
      <div class="detail-title">Consensus</div>
      <div class="detail-line"></div>
      <div class="detail-box-3">
        <div class="detail-box-3-title">・ Transaction validating</div>
        <div class="detail-box-3-content">
          Each validator individually determines whether to accept or deny a
          transaction request and gathers the results in order to participate in
          the consensus. Validators decide whether to accept or deny based on
          two given standards: <br /><br />
          <span class="box-3-italic"
            >- Is the sender really the one who requested the transaction?<br
          /></span>
          Signature, which is generated by a private key, is included in a
          transaction request. One can easily figure out the validity of a
          signature using a public key. And finally, one can trust the public
          key by comparing it to the address that requested the transaction.<br /><br />
          <span class="box-3-italic">- Is this transaction valid?<br /></span>
          Assuming that the sender is the one who requested the transaction,
          transaction itself must now be validated. For example, in the existing
          cryptocurrency networks, the system checks whether the sender has
          enough tokens to satisfy the request and whether the recipient address
          is valid.
        </div>
      </div>
      <div class="detail-box-3">
        <div class="detail-box-3-title">・ Round Validating</div>
        <div class="detail-box-3-content">
          <span class="box-3-bold">1. Round sync<br /></span>
          All validators store the length of their current operating chain and
          we named this value a round. In other words, round is the current
          block number at which a validator is operating within that chain
          lifecycle. In order to reach consensus among themselves, validators
          must check the rounds of other validators. Instead of broadcasting
          one's own round, SASEUL requires a validator to request other
          validators' rounds.<br />
          <img src="../../assets/infographic/Round-Validating1.jpg" />
          <span class="caption">
            Each validator requests rounds from other validators to sync with
            and validate blocks from rounds ahead. </span
          ><br /><br />
          If there is a validator several rounds ahead, other validators who are
          several rounds behind would have to sync all rounds ahead and validate
          those extra rounds. If there are multiple nodes operating ahead, a
          lagging node would sync and validate data from the node operating at
          the highest round. If there are invalid data or transaction included,
          the recipient validator can remove that node from its tracker. If
          there are no validators operating ahead, one can participate in a new
          round and generate blocks with other validators in the same round.
        </div>
        <br /><br />
        <div class="detail-box-3-content">
          <span class="box-3-bold">2. Block generate<br /></span>
          If there are no validators operating ahead, one can generate the block
          for the current round. Each validator would generate a block and the
          consensus for that block would take place in the following round sync.
          In other words, if there is a malicious node including invalid data in
          a block, then that node would be removed from the non-evil nodes'
          trackers and thus will be forked from the network.<br />
          <img src="../../assets/infographic/Round-Validating2.jpg" />
          <span class="caption">
            If there are validators operating in the same round, all validators
            in that round generate a block for that round and compare block hash
            among themselves. If there are invalid block hashes, validators can
            terminate one another from the network.
          </span>
        </div>
        <br /><br />
        <div class="detail-box-3-content">
          <span class="box-3-bold">3. Block commit<br /></span>
          After the block has been generated, validators operating in the same
          round vote using the block hash in order to decide whether to commit
          the block or not. If the hash values are different, one will sync
          block with the validator that delivered the different hash value and
          check for any other differences. Based on the result, one can either
          update to re-commit or completely fork the network. However, no voting
          takes place after the block update voting takes place only once during
          a single round.<br />
          <img src="../../assets/infographic/Round-Validating3.jpg" />
          <span class="caption">
            A block that has reached consensus through voting is committed onto
            each individual chains.
          </span>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "detail-content",
};
</script>

<style scoped>
.detail-content {
  width: 100%;
  margin: 0 auto;
  padding: 0 60px;
  /*max-width: 1024px;*/
}
.detail-box-wrap {
  padding-bottom: 60px;
}
.detail-box-wrap:first-child {
  padding-top: 60px;
}
.detail-title {
  font-size: 24px;
  font-weight: bold;
  color: #82549d;
  padding: 0 0 20px 0;
}
.detail-line {
  border-top: 2px solid #979797;
  padding-bottom: 20px;
}
.detail-box-1 {
  display: flex;
  font-size: 16px;
  line-height: 25px;
  padding: 0 0 30px 0;
  color: #2d2d2d;
}
.detail-box-1:last-child {
  padding-bottom: 0;
}
.detail-img-box {
  /*width: 15%;*/
  min-width: 80px;
  display: flex;
  justify-content: left;
  align-items: center;
}
.detail-text-box {
  text-align: justify;
}
@media (min-width: 481px) and (max-width: 768px) {
  .detail-img-box {
    justify-content: center;
    align-items: flex-start;
    padding-top: 30px;
  }
}
.detail-text-box {
  width: 85%;
  text-align: justify;
}
.detail-bold-text {
  font-weight: bold;
}
.detail-box-2 {
  width: 100%;
}
.detail-box-2 img {
  width: 100%;
}
.detail-box-2-title {
  font-size: 20px;
  font-weight: bold;
  margin-bottom: 10px;
  color: #2d2d2d;
}
.detail-box-3 {
  margin-bottom: 30px;
}
.detail-box-2-content {
  font-size: 16px;
  line-height: 25px;
  color: #2d2d2d;
  text-align: initial;
}
.detail-box-3-title {
  font-size: 20px;
  font-weight: bold;
  margin-bottom: 10px;
  color: #2d2d2d;
}
.box-3-bold {
  font-weight: bold;
}
.box-3-italic {
  font-style: italic;
}
.detail-box-3-content {
  width: 100%;
  font-size: 16px;
  line-height: 25px;
  color: #2d2d2d;
  text-align: justify;
}
.detail-box-3-content img {
  width: 100%;
}
.caption {
  display: inline-block;
  width: 100%;
  font-size: 14px;
  line-height: 21px;
  color: #2d2d2d;
  text-align: center;
}

@media screen and (min-width: 480px) {
  .m_box {
    display: none;
  }
}
@media screen and (max-width: 480px) {
  .detail-box-wrap:first-child {
    padding-top: 0;
  }
  .detail-title {
    font-size: 21px;
  }
  .detail-content {
    padding: 30px 20px;
  }
  .detail-img-box {
    display: none;
  }
  .detail-text-box {
    width: 100%;
    text-align: initial;
  }
  .m_box {
    display: inline-block;
  }
  .m_box_lightnode {
    display: inline-block;
    width: 14px;
    height: 14px;
    margin: 0 6px -1px 0;
    background-color: #d8d8d8;
  }
  .m_box_supervisor {
    display: inline-block;
    width: 14px;
    height: 14px;
    margin: 0 6px -1px 0;
    background-color: #4ca049;
  }
  .m_box_validator {
    display: inline-block;
    width: 14px;
    height: 14px;
    margin: 0 6px -1px 0;
    background-color: #9569ad;
  }
  .m_box_arbiter {
    display: inline-block;
    width: 14px;
    height: 14px;
    margin: 0 6px -1px 0;
    background-color: #58a6cc;
  }
  .detail-bold-text {
    display: inline-block;
  }
  .detail-box-3-content {
    text-align: initial;
  }
}
</style>
